pull_request_rules:
  - name: Auto-merge when approved and checks pass
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Prettier Check
      - check-success!=*
    actions:
      merge:
        method: squash
